#!/usr/bin/env python3
import sys
import os

# Allow running locally, or find packaged code in /usr/share/micro-proton
local_path = os.path.dirname(os.path.abspath(__file__))
pkg_path = "/usr/share/micro-proton"

if os.path.exists(os.path.join(local_path, "src")):
    sys.path.insert(0, local_path)
elif os.path.exists(pkg_path):
    sys.path.insert(0, pkg_path)

from src.ui.manager import main
if __name__ == "__main__":
    main()
